name: Update YouTube Titles
on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  update-titles:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade google-api-python-client google-auth-oauthlib oauth2client
          pip install --upgrade google-auth-httplib2

      - name: Create debug script
        run: |
          cat > debug_check.py << 'EOL'
          import os
          import json
          import sys
          
          print("=== Debug Information ===")
          print(f"Python version: {sys.version}")
          print("\nEnvironment Variables:")
          print(f"MY_VIDEO_ID present: {'MY_VIDEO_ID' in os.environ}")
          print(f"MY_SHORT_ID present: {'MY_SHORT_ID' in os.environ}")
          
          try:
              with open('oauth2.json', 'r') as f:
                  data = json.load(f)
                  print("\nOAuth2 JSON:")
                  print(f"Keys present: {list(data.keys())}")
          except Exception as e:
              print(f"\nError reading oauth2.json: {e}")
          
          print("\n=== End Debug Info ===\n")
          EOL

      - name: Create oauth2.json
        run: |
          echo "${{ secrets.OAUTH_JSON }}" > oauth2.json
          
      - name: Run debug check
        env:
          MY_VIDEO_ID: ${{ secrets.MY_VIDEO_ID }}
          MY_SHORT_ID: ${{ secrets.MY_SHORT_ID }}
        run: python debug_check.py

      - name: Run update script
        env:
          MY_VIDEO_ID: ${{ secrets.MY_VIDEO_ID }}
          MY_SHORT_ID: ${{ secrets.MY_SHORT_ID }}
          PYTHONUNBUFFERED: "1"
        run: python update_title.py
